recipe: default.v1
assistant_id: customer_bot
language: en

pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
- name: SpacyTokenizer
  epochs: 200
- name: RegexFeaturizer
  epochs: 100
- name: LexicalSyntacticFeaturizer
  epochs: 100
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  entity_recognition: True
  epochs: 200
  random_seed: 42
  constrain_similarities: True
- name: RegexEntityExtractor
  use_lookup_tables: True
  epochs: 100
- name: EntitySynonymMapper
  epochs: 100
- name: ResponseSelector
  epochs: 200
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.7

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 200
  random_seed: 42
  constrain_similarities: True
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True

fallbacks:
  nlu_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  ambiguity_threshold: 0.1
